# Generated by Django 4.1 on 2023-04-27 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('prestador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(default='')),
                ('quantidade_horas', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente')),
                ('prestador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestador.prestador')),
            ],
        ),
    ]
