# Generated by Django 4.1 on 2023-04-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('email', models.EmailField(default='', max_length=255)),
            ],
        ),
    ]
