# Generated by Django 4.1 on 2023-05-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="nome",
            field=models.CharField(default="", max_length=16),
            preserve_default=False,
        ),
    ]
